#!/usr/bin/env bash
# Environment setup script - Creates environment variable configuration
#
# Usage:
#   ./env-setup.sh
#
# This script will:
#   - Create ~/.dotfiles_env with environment variables
#   - Configure PATH for various tools
#   - Set up SSH agent auto-start
#   - Add placeholder values for API keys
#   - Add source line to shell rc file

set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/utils.sh"

readonly USER_HOME="$(get_home)"
readonly ENV_FILE="${USER_HOME}/.dotfiles_env"

section "Environment Setup"

info "Creating environment configuration file: $ENV_FILE"

cat > "$ENV_FILE" << 'EOF'
# Dotfiles Environment Variables
# This file is generated by dotfiles/scripts/env-setup.sh
# Source this in your ~/.zshrc or ~/.bashrc: source ~/.dotfiles_env

# ============================================
# API Keys - REPLACE THESE WITH ACTUAL VALUES
# ============================================

# Ref Tools - Documentation search
# Get your key from: https://ref.tools
export REF_API_KEY="${REF_API_KEY:-GET_FROM_https://ref.tools}"

# Context7 - Code context AI
# Get your key from: https://context7.com
export CONTEXT7_API_KEY="${CONTEXT7_API_KEY:-GET_FROM_https://context7.com}"

# Add other API keys as needed
# export ANOTHER_API_KEY="${ANOTHER_API_KEY:-your_key_here}"

# ============================================
# PATH Configuration
# ============================================

# Local binaries
export PATH="$HOME/.local/bin:$PATH"

# Homebrew (macOS ARM)
if [ -d "/opt/homebrew/bin" ]; then
    export PATH="/opt/homebrew/bin:$PATH"
fi

# Bun
if [ -d "$HOME/.bun/bin" ]; then
    export PATH="$HOME/.bun/bin:$PATH"
fi

# Mise (version manager)
if [ -f "$HOME/.local/bin/mise" ]; then
    eval "$($HOME/.local/bin/mise activate bash 2>/dev/null || true)"
fi

# Cargo (Rust)
if [ -f "$HOME/.cargo/env" ]; then
    source "$HOME/.cargo/env"
fi

# ============================================
# Tool Configuration
# ============================================

# Default editor
export EDITOR="nvim"
export VISUAL="$EDITOR"

# Less configuration
export LESS="-R"

# FZF configuration
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

# ============================================
# SSH Agent (Auto-start)
# ============================================

if [ -z "$SSH_AUTH_SOCK" ]; then
    eval "$(ssh-agent -s)" > /dev/null 2>&1
    # Add your SSH keys here if they exist
    if [ -f ~/.ssh/id_ed25519_github ]; then
        ssh-add ~/.ssh/id_ed25519_github 2>/dev/null
    fi
fi

# ============================================
# Starship Prompt (if installed)
# ============================================

if command -v starship &>/dev/null; then
    eval "$(starship init bash 2>/dev/null || true)"
fi
EOF

success "Created environment file: $ENV_FILE"

# Check if already sourced in shell rc
SHELL_RC=""
if [ -f "$USER_HOME/.zshrc" ]; then
    SHELL_RC="$USER_HOME/.zshrc"
elif [ -f "$USER_HOME/.bashrc" ]; then
    SHELL_RC="$USER_HOME/.bashrc"
fi

if [ -n "$SHELL_RC" ]; then
    if grep -q "source.*\.dotfiles_env" "$SHELL_RC"; then
        success "Already sourced in $SHELL_RC"
    else
        info "Adding source line to $SHELL_RC"
        echo "" >> "$SHELL_RC"
        echo "# Dotfiles environment configuration" >> "$SHELL_RC"
        echo "[ -f ~/.dotfiles_env ] && source ~/.dotfiles_env" >> "$SHELL_RC"
        success "Added to $SHELL_RC"
    fi
fi

echo ""
warning "IMPORTANT: You must edit $ENV_FILE and add your actual API keys!"
echo ""
info "To edit: $EDITOR $ENV_FILE"
info "Then reload: source $ENV_FILE"
echo ""
