# NixOS Desktop x86_64 Configuration
#
# This configuration imports hardware-configuration.nix from /etc/nixos/
# which is generated by nixos-generate-config and stays local to each machine.
#
# SETUP:
#   1. Run 'sudo nixos-generate-config' on the target machine
#   2. Rebuild with: sudo nixos-rebuild switch --flake .#nixos-desktop-x86 --impure
#
# The --impure flag is required because we import from outside the flake.

{ config, lib, pkgs, inputs, username, ... }:

{
  imports = [
    # Import machine-specific hardware config from standard NixOS location
    # This file is generated by nixos-generate-config and not tracked in git
    /etc/nixos/hardware-configuration.nix
    ../../modules/nixos/base.nix
    ../../modules/nixos/graphical.nix
  ];

  # Host-specific configuration
  networking.hostName = "nixos-desktop-x86";

  # Ensure we're on x86_64
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Override state version for this specific host
  system.stateVersion = "25.05";
}
